### ISSUE TITLE
Save tags/priority against the server connection - not only the course

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/moodle-block_oppia_mobile_export#128]
Currently on export the tags/priority are only stored against a course n the Moodle server, should store against combination of the course and Oppia server connection, in case the same course is exported to different Oppia servers and with different tags/priority.

Will need an extra column in the mdl_block_oppia_mobile_config table

**Comment by jjoseba** [comment]
And the sequencing mode? Maybe in different servers there are different needs in terms of that functionality.

**Comment by alexlittle** [comment]
Yes please!

It's just so we have the flexibility of publishing the same course for 
different Oppia implementations, even if they may have slightly 
different requirements.

Cheers,
Alex

On 10/02/16 11:56, Joseba S. wrote:
>
> And the sequencing mode? Maybe in different servers there are 
> different needs in terms of that functionality.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DigitalCampus/moodle-block_oppia_mobile_export/issues/128#issuecomment-182285134>.
>

-- 
Alex Little
alex@alexlittle.net
http://alexlittle.net
mobile (UK): +44 7548 236 650
skype: alexlittleou
twitter: @alexlittle <https://twitter.com/alexlittle>
