### ISSUE TITLE
Error in xml "failed to load external entity " when trying to export course

### ISSUE THREAD

**Issue by florencejones** [DigitalCampus/moodle-block_oppia_mobile_export#130]
Hello,
I just did a new installation of oppia and moodle and trying to test course upload in moodle does not seem to work. I cannot get past the course export page as it gives me the error "failed to load external entity"

**Comment by alexlittle** [comment]
Hi Florence,

Do you have a link to the course in Moodle that you could send on? 
Alternatively if you could send on a Moodle backup of the course, so I 
can see what might be going wrong here.

Cheers,
Alex

On 05/11/15 07:44, florencejones wrote:
>
> Hello,
> I just did a new installation of oppia and moodle and trying to test 
> course upload in moodle does not seem to work. I cannot get past the 
> course export page as it gives me the error "failed to load external 
> entity"
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DigitalCampus/moodle-block_oppia_mobile_export/issues/130>.
>


-- 
Alex Little
Director, Digital Campus
alex@digital-campus.org
http://digital-campus.org
mobile (UK): +44 7548 236 650
skype: alexlittleou
twitter: @digicampusteam <https://twitter.com/digicampusteam> & 
@alexlittle <https://twitter.com/alexlittle>

**Comment by florencejones** [comment]
Hello Alex,
This is a moodle backup of the course I have been trying to export. Please
find attached
Thanks

On Mon, Nov 9, 2015 at 3:51 PM, Alex Little <notifications@github.com>
wrote:

> Hi Florence,
>
> Do you have a link to the course in Moodle that you could send on?
> Alternatively if you could send on a Moodle backup of the course, so I
> can see what might be going wrong here.
>
> Cheers,
> Alex
>
> On 05/11/15 07:44, florencejones wrote:
> >
> > Hello,
> > I just did a new installation of oppia and moodle and trying to test
> > course upload in moodle does not seem to work. I cannot get past the
> > course export page as it gives me the error "failed to load external
> > entity"
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/DigitalCampus/moodle-block_oppia_mobile_export/issues/130
> >.
> >
>
>
> --
> Alex Little
> Director, Digital Campus
> alex@digital-campus.org
> http://digital-campus.org
> mobile (UK): +44 7548 236 650
> skype: alexlittleou
> twitter: @digicampusteam <https://twitter.com/digicampusteam> &
> @alexlittle <https://twitter.com/alexlittle>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DigitalCampus/moodle-block_oppia_mobile_export/issues/130#issuecomment-155102285>
> .
>



-- 

*Florence Lomotiorkor Jones*

Software Developer



Grameen Foundation
Office:  No. 25 Labone Cresent
Postal: OSDTD5041, No. 25 Labone Crescent, Labone, Accra, Ghana

Mobile: +233 (0)54 0100773
Email:fjones*@grameenfoundation.org <ayeboah@grameenfoundation.org>*

Skype ID: florence-jones

" *Do not be anxious about anything, but in every situation, by prayer and
petition, with thanksgiving, present your requests to God.** And the peace
of God, which transcends all understanding,will guard your hearts and your
minds in Christ Jesus. Philippians 4:6-7*"

**Comment by alexlittle** [comment]
Hi Florence, thanks for sending on the course back up. Have just had a look at this on my laptop install of Moodle & Oppia. The issue is to do with the long section titles (the "lorem ipsum..." bit), as these title contain a lot of html and html entities that won;t get represented in the final app output .

So if these are changed to much shorter titles (as they will end up getting displayed in the app), then it should export fine.

Of course, we should also make sure the error messages produced are more meaningful on export.
