### ISSUE TITLE
There was an error creating the quiz, please try exporting this course again (refresh this page) ( status code: 302)

### ISSUE THREAD

**Issue by florencejones** [DigitalCampus/moodle-block_oppia_mobile_export#133]
Hello, 
I have an issue exporting a course that contains quizzes. This is the error:
There was an error creating the quiz, please try exporting this course again (refresh this page) ( status code: 302)
Error connecting to OppiaMobile server, please check the your API url, username and API key.

**Comment by alexlittle** [comment]
Hi Florence,

The HTTP status code 302 code means there is a redirection taking place 
when connecting to the Oppia server for creating the quiz.

I thought it may be if there wasn't a trailing '/' on the server name 
(in the Oppia export block server setting in Moodle), but I tested on my 
machine and it seems to be work with/without a trailing '/' so don;t 
think it;s that.

Where do you have your Oppia server running?

Cheers,
Alex

On 26/11/15 12:57, florencejones wrote:
>
> Hello,
> I have an issue exporting a course that contains quizzes. This is the 
> error:
> There was an error creating the quiz, please try exporting this course 
> again (refresh this page) ( status code: 302)
> Error connecting to OppiaMobile server, please check the your API url, 
> username and API key.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DigitalCampus/moodle-block_oppia_mobile_export/issues/133>.
>


-- 
Alex Little
Director, Digital Campus
alex@digital-campus.org
http://digital-campus.org
mobile (UK): +44 7548 236 650
skype: alexlittleou
twitter: @digicampusteam <https://twitter.com/digicampusteam> & 
@alexlittle <https://twitter.com/alexlittle>

**Comment by alexlittle** [comment]
Cannot replicate - so closing for now
