### ISSUE TITLE
Page/Settings button disappeared - conflict with new styles applied?

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/moodle-block_oppia_mobile_export#147]
With the new style sheet applied (in https://github.com/DigitalCampus/moodle-block_oppia_mobile_export/issues/94) the save buttons disappear on the course edit settings page and also on some of the activity editing pages. Suspect the new styles have something to do with this?

To recreate (tested with both the Moodle default 'clean' theme and also the Digital Campus one):

1. checkout the master branch (this already has #94 changes merged in)
2. In Moodle, click on the purge caches option - at the very bottom of the page (this ensures the stylesheets etc aren't being kept form previous version)
3. In any course go to the edit settings page
4. You won't see the "save changes" or "cancel" buttons/links - so you can't save any of the changes
5. Now checkout the previous version of the block (tagged 'v2016022400') and repeat the purge and go back to the course settings page, the buttons will have re-appeared

**Comment by alexlittle** [comment]
There still seem to be some issues:

styles on many buttons is changed (loss of padding around text and also some text is now in bold), eg the 'turn editing on' button: 
![button](https://cloud.githubusercontent.com/assets/344917/13526720/7dbd8a2c-e212-11e5-8dd0-e6ece71c93da.png)

Unclear to me if there are other issues too that I've not yet found.

Can we put the new export block styles within their own div->id or with class-prefix, so then we can be more sure there aren't other conflicts?

**Comment by jjoseba** [comment]
The CSS that seems to cause that zero padding and margin issue to buttons and other block elements comes from the theme CSS, not the new added block (http://moodle.digital-campus.org/theme/yui_combo.php?3.17.2/cssreset/cssreset-min.css&3.17.2/cssfonts/cssfonts-min.css&3.17.2/cssgrids/cssgrids-min.css&3.17.2/cssbase/cssbase-min.css - line 8).

I've just made a new pull request removing keeping only styles with class prefix.
