### ISSUE TITLE
Install/Upgrade process styling compatible with newer Moodle versions

### ISSUE THREAD

**Issue by jjoseba** [DigitalCampus/moodle-block_oppia_mobile_export#169]
Right now the page with the results of the installation/upgrade of the Moodle block is not working well with new versions of Moodle, displaying an unstyled page:
![image](https://cloud.githubusercontent.com/assets/6810415/22826321/1d96a30c-ef92-11e6-839a-bfb2f3aebf7e.png)

**Comment by alexlittle** [comment]
Thanks Joseba, on the more recent version of Moodle (esp 3.2+) there are quite a lot of changes in how the stylesheets etc work as they have much better (but very different) themes (esp for mobile/tablet layout

**Comment by alexlittle** [comment]
Closing as no longer an issue?
