### ISSUE TITLE
Adding feedback for matching question type

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/moodle-block_oppia_mobile_export#3]
Can use the 'totally incorrect/partially correct/fully correct' feedback options in Moodle for this

**Comment by jjoseba** [comment]
It is already included in the quiz JSON, in the properties `partiallycorrectfeedback`, `correctfeedback` and `incorrectfeedback` inside the `props` array. Should have been implemented some time in the past but the issue was never closed. What is now pending is to implement it in the app.
